name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: upload to PyPI
    runs-on: ubuntu-latest
    environment: release  # must match PyPI Trusted Publisher config
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache-dependency-path: pyproject.toml

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish

      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install build

      - name: Build distribution
        run: python -m build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
